---
title: "PFR Prototype 1"
output:
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
    
runtime: shiny
---

```{r global, include=FALSE}
message("Loading libraries")
library(flexdashboard)
library(shiny)

options(error = function() traceback(3))
  
message("Loading globals")
source("utils.R")
# conn <- db_connect()

vals = reactiveValues()
vals$records <-
  data.frame(
    id = c(),
    name = c(),
    type = c(),
    amount = c(),
    freq = c(),
    datetime_added = c(),
    datetime_added_str = c(),
    mthly_equiv = c()
  )

vals$idctr = 0

#' Add a record to the transaction table
add_record <- function(n, t, a, f) {
  rid = vals$idctr + 1
  vals$idctr = rid

  dttm_add = Sys.time()
  mthly =
    a *
    switch(
      f,
      daily = 4.28*7,
      workdays = 4.28*5,
      weekly = 4.28,
      monthly = 1,
      yearly = 1/12
    )
    
  vals$records[
    nrow(vals$records) + 1,
    c(
      "id", "name", "type", "amount", "freq",
      "datetime_added", "datetime_added_str", "mthly_equiv"
    )
  ] =
    c(rid, n, t, a, f, dttm_add, strftime(dttm_add, "%Y-%m-%dT%H:%M:%S"), mthly)

  rid
}

#' Remove a record from the transactions table
rm_record <- function(rid) {

  if (!(rid %in% vals$records[["id"]])) {
    stop(sprintf("cannot remove record: id %i is invalid", rid))
  }

  keep = vals$records[["id"]] != rid
  rcrd = vals$records[!keep,]
  vals$records <- vals$records[keep,]

  rcrd

}
```

Add a transaction {.sidebar data-width=300}
=====================================================================

### Add a transaction

```{r}
textInput("name", "What's the name of this transaction?")

radioButtons("type", "Is this income or expenditure?",
  choices = list("Income" = "income", "Expenditure" = "expense")
)

numericInput("amount", "What is the value of this transaction?", NA)

radioButtons("freq", "How often does this transaction occur?",
  choices = list(
    "Once per day" = "daily",
    "Once per workday (Mon-Fri)" = "workdays",
    "Once per week" = "weekly",
    "Once per month" = "monthly",
    "Once per year" = "yearly"
  )
)

actionButton("submit", "Add Transaction", class = "btn-primary")

observeEvent(input$submit, {
  add_record(input$name, input$type, input$amount, input$freq)
  message("response submitted")
})
```

### Remove a transaction

```{r}
numericInput("trns_rm_id", "Enter the transaction ID to remove", NA)

actionButton("trns_rm", "Remove Transaction", class = "btn-primary")

observeEvent(input$trns_rm, {
  rm_record(input$trns_rm_id)
  message("response submitted")
})
```

Transactions Page
=====================================================================

Transactions Table Row 
---------------------------------------------------------------------

### Transactions Table

```{r}
renderTable({
  message("updating table")
  vals$records
})
```

Summary Boxes Row
---------------------------------------------------------------------

### Transactions recorded

```{r}
renderValueBox({
  n_records <- nrow(vals$records)
  valueBox(n_records)
})
```

### Monthly Income

```{r}
renderValueBox({

  mthly = 0

  if (nrow(vals$records) != 0) {
    incomes = vals$records[vals$records[,"type"] == "income",c("mthly_equiv")]

    if (nrow(incomes) != 0) {
      for (i in 1:nrow(incomes)) {
        mthly = mthly + as.numeric(incomes[i,"mthly_equiv"])
      }

    }

  }

  valueBox(sprintf("$%.2f", mthly))
})
```

### Monthly Expenses

```{r}
renderValueBox({
  mthly = 0

  if (nrow(vals$records) != 0) {
    incomes = vals$records[vals$records[,"type"] == "expense",c("mthly_equiv")]

    if (nrow(incomes) != 0) {
      for (i in 1:nrow(incomes)) {
        mthly = mthly + as.numeric(incomes[i,"mthly_equiv"])
      }

    }

  }

  valueBox(sprintf("$%.2f", mthly))
})
```

### Monthly Net

```{r}
renderValueBox({
  mthly = 0

  if (nrow(vals$records) != 0) {
    incomes = vals$records[,c("mthly_equiv", "type")]

    if (nrow(incomes) != 0) {
      for (i in 1:nrow(incomes)) {
        mthly =
          mthly + 
          as.numeric(incomes[i,"mthly_equiv"]) *
          switch(
            incomes[i,"type"],
            expense = -1,
            income = 1
          )
      }

    }

  }

  valueBox(
    sprintf("$%.2f", mthly),
    color = ifelse(mthly <= 0, "warning", "primary")
  )
})
```

Monthly Report
=====================================================================

```{r}
renderText("Coming Soon!")
```
